// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4All_VtqrlB3Gd0i-gKmaexoTLXpkjM',
    appId: '1:499144810920:web:6cc78cca9667626b253d9d',
    messagingSenderId: '499144810920',
    projectId: 'flutter-firebase-app-a310a',
    authDomain: 'flutter-firebase-app-a310a.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-a310a.firebasestorage.app',
    measurementId: 'G-S57Z18RHGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpsDNC6fV3C8n-QjhynBr9cK3JAyuQreY',
    appId: '1:499144810920:android:febdfb60aae9780f253d9d',
    messagingSenderId: '499144810920',
    projectId: 'flutter-firebase-app-a310a',
    storageBucket: 'flutter-firebase-app-a310a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjX-aWTSL_3LGHZS6EB5IWKQFy5j8j4ww',
    appId: '1:499144810920:ios:d9a079a37c9e95ed253d9d',
    messagingSenderId: '499144810920',
    projectId: 'flutter-firebase-app-a310a',
    storageBucket: 'flutter-firebase-app-a310a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjX-aWTSL_3LGHZS6EB5IWKQFy5j8j4ww',
    appId: '1:499144810920:ios:d9a079a37c9e95ed253d9d',
    messagingSenderId: '499144810920',
    projectId: 'flutter-firebase-app-a310a',
    storageBucket: 'flutter-firebase-app-a310a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH4All_VtqrlB3Gd0i-gKmaexoTLXpkjM',
    appId: '1:499144810920:web:58623436f5da337b253d9d',
    messagingSenderId: '499144810920',
    projectId: 'flutter-firebase-app-a310a',
    authDomain: 'flutter-firebase-app-a310a.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-a310a.firebasestorage.app',
    measurementId: 'G-6C9DG22GLK',
  );
}
